# Generated by Django 5.2.13 on 2026-05-02 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_ugc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sorted',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AlterField(
            model_name='survey',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_author', to='surveys_ugc.author'),
        ),
        migrations.CreateModel(
            name='AnswerToQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.TextField(help_text='Ответ')),
                ('sorted', models.PositiveIntegerField()),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answertoquestion_question', to='surveys_ugc.question')),
                ('survey', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answertoquestion_survey', to='surveys_ugc.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
