# Generated by Django 5.2.13 on 2026-05-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_ugc', '0002_remove_question_sorted_remove_question_survey_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertoquestion',
            name='sorted',
        ),
        migrations.AddField(
            model_name='question',
            name='sorted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
