# Generated by Django 5.2.13 on 2026-05-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_ugc', '0003_remove_answertoquestion_sorted_question_sorted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
