# Generated by Django 5.2.13 on 2026-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_ugc', '0004_remove_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertoquestion',
            name='sorted',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
