# Generated by Django 5.2.13 on 2026-05-02 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_ugc', '0005_answertoquestion_sorted'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.BooleanField(default=False, help_text='Ответ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answertoquestion',
            name='user_response',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answertoquestion_userresponse', to='surveys_ugc.userresponse'),
        ),
    ]
