# Generated by Django 5.2.13 on 2026-05-02 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_ugc', '0006_userresponse_answertoquestion_user_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertoquestion',
            name='user_response',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='answer_to_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userresponse_answertoquestion', to='surveys_ugc.answertoquestion'),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='userresponse_author', to='surveys_ugc.author'),
        ),
    ]
