# Generated by Django 5.2.13 on 2026-05-03 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_ugc', '0007_remove_answertoquestion_user_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertoquestion',
            name='survey',
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='answertoquestion_survey', to='surveys_ugc.survey'),
        ),
    ]
