# Generated by Django 5.2.13 on 2026-05-03 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys_ugc', '0008_remove_answertoquestion_survey_question_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='question_survey', to='surveys_ugc.survey'),
        ),
    ]
